{"name": "Логин существующим пользователем", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range", "trace": "self = <tests.login_test.TestLogin object at 0x000001F0BF75CE90>, user_fixture = []\n\n    @allure.title('Логин существующим пользователем')\n    @allure.description('Проверяем, что при логине существующим пользователем воозвращается код 200')\n    def test_existing_user_login_successful(self, user_fixture):\n>       response = helper_user.login_user(user_fixture[0], user_fixture[1])\nE       IndexError: list index out of range\n\ntests\\login_test.py:10: IndexError"}, "description": "Проверяем, что при логине существующим пользователем воозвращается код 200", "start": 1711898049938, "stop": 1711898049938, "uuid": "e79f4055-1fcd-4aff-88d0-c5feb7cd7c06", "historyId": "29270087448cd3e901130b9d7ba97d6b", "testCaseId": "29270087448cd3e901130b9d7ba97d6b", "fullName": "tests.login_test.TestLogin#test_existing_user_login_successful", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "login_test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-PR51OJ8"}, {"name": "thread", "value": "23212-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.login_test"}]}