{"name": "Логин несуществующим пользователем", "status": "passed", "description": "Проверяем, что при логине несуществующим пользователем возвращается \"success\": false", "steps": [{"name": "Логин пользователя", "status": "passed", "parameters": [{"name": "email", "value": "'unexisting'"}, {"name": "password", "value": "'unexisting'"}], "start": 1711898050813, "stop": 1711898051476}], "start": 1711898050813, "stop": 1711898051476, "uuid": "b64a06b9-0966-427c-adbf-d8d439117e96", "historyId": "73a7748b144b78b761493b3dfcd1be80", "testCaseId": "73a7748b144b78b761493b3dfcd1be80", "fullName": "tests.login_test.TestLogin#test_not_existing_user_login_unsuccessful", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "login_test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-PR51OJ8"}, {"name": "thread", "value": "23212-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.login_test"}]}